name: Main PR/MG Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    branches: main
  merge_group:
    branches: main

jobs:
    call-reusable-workflow:
      if: ${{ github.event_name == 'merge_group' }}
      uses: ./.github/workflows/reusable-pr-mr.yml
      with:
        github_event_name: ${{ github.event_name }}