name: Reusable PR/MG Workflow

on:
  workflow_call:
    inputs:
      github_event_name:
        required: true
        type: string

jobs:
    validate:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - run: echo "Validating..."
          
    deploy-to-staging:
        concurrency: deploy-to-staging
        if: ${{ inputs.github_event_name == 'merge_group' }}
        environment: Staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Deploying..."

    deploy-to-production:
        concurrency: deploy-to-production
        if: ${{ inputs.github_event_name == 'merge_group' }}
        environment: Production
        needs: deploy-to-staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Deploying..."