name: Reusable PR/MG Workflow

on:
  workflow_call

jobs:
    deploy-to-staging:
        concurrency: deploy-to-staging
        environment: Staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Deploying..."

    deploy-to-production:
        concurrency: deploy-to-production
        environment: Production
        needs: deploy-to-staging
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Deploying..."